In [58]:
import pandas as pd
#import chart_studio.plotly as py
import plotly.offline as py
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import pandas as pd
import numpy as np
import plotly.express as px
#py.sign_in(username='', api_key='')
init_notebook_mode(connected=True)

In [27]:
df = pd.read_csv('dataset/commodity/Exchange rates 2011-2019.txt', sep="\t", header=None)
df.columns = ["Month", "USD_MYR", "SGD_MYR", "GBP_MYR","EUR_MYR"]

In [28]:
df = df[1:]

In [29]:
df['Month']=pd.to_datetime(df['Month'],format='%d/%m/%y')

In [30]:
df=df.sort_values('Month')
#df = df.set_index('Month')

In [31]:
df.head()

        Month USD_MYR SGD_MYR GBP_MYR EUR_MYR
95 2011-01-06  3.0195  2.4591  4.8453  4.3801
94 2011-01-07  2.9655  2.4632  4.8695  4.2691
93 2011-01-08   2.983  2.4771  4.8486  4.2891
92 2011-01-09  3.1885  2.4388  4.9691  4.2682
91 2011-01-10   3.068  2.4451   4.936  4.2517

In [37]:
USD_MYR = go.Scatter(
    x=df.Month,
    y=df['USD_MYR'],
    name = "USD_MYR",
    line = dict(color = '#17BECF'),
    opacity = 0.8)

SGD_MYR = go.Scatter(
     x=df.Month,
    y=df['SGD_MYR'],
    name = "SGD_MYR",
    line = dict(color = '#7F7F7F'),
    opacity = 0.8)

GBP_MYR = go.Scatter(
     x=df.Month,
    y=df['GBP_MYR'],
    name = "GBP_MYR",
    line =  dict(color = 'blue'),
                opacity = 0.8)

EUR_MYR = go.Scatter(
     x=df.Month,
    y=df['EUR_MYR'],
    name = "EUR_MYR",
    line =  dict(color = 'green'),
                opacity = 0.8)

data = [USD_MYR,SGD_MYR,GBP_MYR,EUR_MYR]

layout = dict(
    title='Exchange rates 2011-2019',
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=1,
                     label='1m',
                     step='month',
                     stepmode='backward'),
                dict(count=6,
                     label='6m',
                     step='month',
                     stepmode='backward'),
                dict(step='all')
            ])
        ),
        rangeslider=dict(
            visible = True
        ),
        type='date'
    )
)

fig = dict(data=data, layout=layout)
py.iplot(fig, filename = "Exchange rates 2011-2019")

In [15]:
brent_df = pd.read_csv('dataset/commodity/Brent Oil Historical price 2011-19.txt',sep="\t", header=None)
brent_df.columns = ["Month", "Price(USD)", "Change %"]
brent_df = brent_df[1:]
brent_df = brent_df.reset_index(drop = True)
brent_df['Month']=pd.to_datetime(brent_df['Month'],format='%d/%m/%y')
brent_df=brent_df.sort_values('Month')

In [16]:
Price = go.Scatter(
    x=brent_df.Month,
    y=brent_df['Price(USD)'],
    name = "Price(USD)",
    line = dict(color = '#17BECF'),
    opacity = 0.8)

Change = go.Scatter(
     x=brent_df.Month,
    y=brent_df['Change %'],
    name = "Change %",
    line = dict(color = '#7F7F7F'),
    opacity = 0.8)

data = [Price,Change]

layout = dict(
    title='Brent Oil Historical price 2011-19',
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=1,
                     label='1m',
                     step='month',
                     stepmode='backward'),
                dict(count=6,
                     label='6m',
                     step='month',
                     stepmode='backward'),
                dict(step='all')
            ])
        ),
        rangeslider=dict(
            visible = True
        ),
        type='date'
    )
)

fig = dict(data=data, layout=layout)
py.iplot(fig, filename = "Brent Oil Historical price 2011-19")

In [17]:
brent_df.head()

        Month Price(USD) Change %
94 2011-01-06     112.48   -3.64%
93 2011-01-07     116.74    3.79%
92 2011-01-08     114.85   -1.62%
91 2011-01-09     102.76  -10.53%
90 2011-01-10     109.56    6.62%

In [18]:
copper_df = pd.read_csv('dataset/commodity/Copper Historical price 2011-19.txt',sep="\t", header=None)
copper_df.columns = ["Month", "Price(USD)", "Change %"]
copper_df = copper_df[1:]
copper_df = copper_df.reset_index(drop = True)
copper_df['Month']=pd.to_datetime(copper_df['Month'],format='%d/%m/%y')
copper_df=copper_df.sort_values('Month')
copper_df.head()

        Month Price(USD) Change %
94 2011-01-06      4.272    2.37%
93 2011-01-07      4.474    4.73%
92 2011-01-08      4.187   -6.41%
91 2011-01-09      3.145  -24.89%
90 2011-01-10      3.629   15.39%

In [19]:
Price = go.Scatter(
    x=copper_df.Month,
    y=copper_df['Price(USD)'],
    name = "Price(USD)",
    line = dict(color = '#17BECF'),
    opacity = 0.8)

Change = go.Scatter(
     x=copper_df.Month,
     y=copper_df['Change %'],
     name = "Change %",
     line = dict(color = '#7F7F7F'),
     opacity = 0.8)

data = [Price,Change]

layout = dict(
    title='Copper Historical price 2011-19',
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=1,
                     label='1m',
                     step='month',
                     stepmode='backward'),
                dict(count=6,
                     label='6m',
                     step='month',
                     stepmode='backward'),
                dict(step='all')
            ])
        ),
        rangeslider=dict(
            visible = True
        ),
        type='date'
    )
)

fig = dict(data=data, layout=layout)
py.iplot(fig, filename = "Copper Historical price 2011-19")

In [20]:
iron_df = pd.read_csv('dataset/commodity/Iron Ore Historical price 2011-19.txt',sep="\t", header=None)
iron_df.columns = ["Month", "Price(USD)", "Change %"]
iron_df = iron_df[1:]
iron_df = iron_df.reset_index(drop = True)
iron_df['Month']=pd.to_datetime(iron_df['Month'],format='%d/%m/%y')
iron_df=iron_df.sort_values('Month')
iron_df.head()

        Month Price(USD) Change %
94 2011-01-06        164   -2.73%
93 2011-01-07      173.1    5.55%
92 2011-01-08      177.4    2.48%
91 2011-01-09      177.5    0.06%
90 2011-01-10      150.4  -15.27%

In [21]:
Price = go.Scatter(
    x=iron_df.Month,
    y=iron_df['Price(USD)'],
    name = "Price(USD)",
    line = dict(color = '#17BECF'),
    opacity = 0.8)

Change = go.Scatter(
     x=iron_df.Month,
     y=iron_df['Change %'],
     name = "Change %",
     line = dict(color = '#7F7F7F'),
     opacity = 0.8)

data = [Price,Change]

layout = dict(
    title='Iron Ore Historical price 2011-19',
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=1,
                     label='1m',
                     step='month',
                     stepmode='backward'),
                dict(count=6,
                     label='6m',
                     step='month',
                     stepmode='backward'),
                dict(step='all')
            ])
        ),
        rangeslider=dict(
            visible = True
        ),
        type='date'
    )
)

fig = dict(data=data, layout=layout)
py.iplot(fig, filename = "Iron Ore Historical price 2011-19")

In [22]:
zinc_df = pd.read_csv('dataset/commodity/Zinc Historical price 2011-19.txt',sep="\t", header=None)
zinc_df.columns = ["Month", "Price(USD)", "Change %"]
zinc_df = zinc_df[1:]
zinc_df = zinc_df.reset_index(drop = True)
zinc_df['Month']=pd.to_datetime(zinc_df['Month'],format='%d/%m/%y')
zinc_df=zinc_df.sort_values('Month')
zinc_df.head()

        Month Price(USD) Change %
94 2011-01-06    2346.25    3.59%
93 2011-01-07       2505    6.77%
92 2011-01-08     2290.5   -8.56%
91 2011-01-09     1866.5  -18.51%
90 2011-01-10     1974.5    5.79%

In [23]:
Price = go.Scatter(
    x=zinc_df.Month,
    y=zinc_df['Price(USD)'],
    name = "Price(USD)",
    line = dict(color = '#17BECF'),
    opacity = 0.8)

Change = go.Scatter(
     x=zinc_df.Month,
     y=zinc_df['Change %'],
     name = "Change %",
     line = dict(color = '#7F7F7F'),
     opacity = 0.8)

data = [Price,Change]

layout = dict(
    title='Zinc Historical price 2011-19',
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=1,
                     label='1m',
                     step='month',
                     stepmode='backward'),
                dict(count=6,
                     label='6m',
                     step='month',
                     stepmode='backward'),
                dict(step='all')
            ])
        ),
        rangeslider=dict(
            visible = True
        ),
        type='date'
    )
)

fig = dict(data=data, layout=layout)
py.iplot(fig, filename = "Zinc Historical price 2011-19")

In [24]:
nickel_df = pd.read_csv('dataset/commodity/Nickel Historical price 2011-19.txt',sep="\t", header=None)
nickel_df.columns = ["Month", "Price(USD)", "Change %"]
nickel_df = nickel_df[1:]
nickel_df = nickel_df.reset_index(drop = True)
nickel_df['Month']=pd.to_datetime(nickel_df['Month'],format='%d/%m/%y')
nickel_df=nickel_df.sort_values('Month')
nickel_df.head()

        Month Price(USD) Change %
94 2011-01-06      23425   -0.11%
93 2011-01-07      24756    5.68%
92 2011-01-08      22245  -10.14%
91 2011-01-09      17625  -20.77%
90 2011-01-10      19555   10.95%

In [25]:
Price = go.Scatter(
    x=nickel_df.Month,
    y=nickel_df['Price(USD)'],
    name = "Price(USD)",
    line = dict(color = '#17BECF'),
    opacity = 0.8)

Change = go.Scatter(
     x=nickel_df.Month,
     y=nickel_df['Change %'],
     name = "Change %",
     line = dict(color = '#7F7F7F'),
     opacity = 0.8)

data = [Price,Change]

layout = dict(
    title='Nickel Historical price 2011-19',
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=1,
                     label='1m',
                     step='month',
                     stepmode='backward'),
                dict(count=6,
                     label='6m',
                     step='month',
                     stepmode='backward'),
                dict(step='all')
            ])
        ),
        rangeslider=dict(
            visible = True
        ),
        type='date'
    )
)

fig = dict(data=data, layout=layout)
py.iplot(fig, filename = "Nickel Historical price 2011-19")