In [16]:
#https://www.analyticsvidhya.com/blog/2018/09/multivariate-time-series-guide-forecasting-modeling-python-codes/
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [22]:
df = pd.read_csv("AirQualityUCI.csv",error_bad_lines=False,parse_dates=[['Date', 'Time']])

b'Skipping line 9359: expected 15 fields, saw 16\nSkipping line 9360: expected 15 fields, saw 16\nSkipping line 9361: expected 15 fields, saw 16\nSkipping line 9362: expected 15 fields, saw 16\nSkipping line 9363: expected 15 fields, saw 16\nSkipping line 9364: expected 15 fields, saw 16\nSkipping line 9365: expected 15 fields, saw 16\nSkipping line 9366: expected 15 fields, saw 16\nSkipping line 9367: expected 15 fields, saw 16\nSkipping line 9368: expected 15 fields, saw 16\nSkipping line 9369: expected 15 fields, saw 16\nSkipping line 9370: expected 15 fields, saw 16\nSkipping line 9371: expected 15 fields, saw 16\nSkipping line 9372: expected 15 fields, saw 16\nSkipping line 9373: expected 15 fields, saw 16\nSkipping line 9374: expected 15 fields, saw 16\nSkipping line 9375: expected 15 fields, saw 16\nSkipping line 9376: expected 15 fields, saw 16\nSkipping line 9377: expected 15 fields, saw 16\nSkipping line 9378: expected 15 fields, saw 16\nSkipping line 9379: expected 15 fields, saw 16\nSkipping line 9380: expected 15 fields, saw 16\nSkipping line 9381: expected 15 fields, saw 16\nSkipping line 9382: expected 15 fields, saw 16\nSkipping line 9383: expected 15 fields, saw 16\nSkipping line 9384: expected 15 fields, saw 16\nSkipping line 9385: expected 15 fields, saw 16\nSkipping line 9386: expected 15 fields, saw 16\nSkipping line 9387: expected 15 fields, saw 16\nSkipping line 9388: expected 15 fields, saw 16\nSkipping line 9389: expected 15 fields, saw 16\nSkipping line 9390: expected 15 fields, saw 16\nSkipping line 9391: expected 15 fields, saw 16\nSkipping line 9392: expected 15 fields, saw 16\nSkipping line 9393: expected 15 fields, saw 16\nSkipping line 9394: expected 15 fields, saw 16\nSkipping line 9395: expected 15 fields, saw 16\nSkipping line 9396: expected 15 fields, saw 16\nSkipping line 9397: expected 15 fields, saw 16\nSkipping line 9398: expected 15 fields, saw 16\nSkipping line 9399: expected 15 fields, saw 16\nSkipping line 9400: expected 15 fields, saw 16\nSkipping line 9401: expected 15 fields, saw 16\nSkipping line 9402: expected 15 fields, saw 16\nSkipping line 9403: expected 15 fields, saw 16\nSkipping line 9404: expected 15 fields, saw 16\nSkipping line 9405: expected 15 fields, saw 16\nSkipping line 9406: expected 15 fields, saw 16\nSkipping line 9407: expected 15 fields, saw 16\nSkipping line 9408: expected 15 fields, saw 16\nSkipping line 9409: expected 15 fields, saw 16\nSkipping line 9410: expected 15 fields, saw 16\nSkipping line 9411: expected 15 fields, saw 16\nSkipping line 9412: expected 15 fields, saw 16\nSkipping line 9413: expected 15 fields, saw 16\nSkipping line 9414: expected 15 fields, saw 16\nSkipping line 9415: expected 15 fields, saw 16\nSkipping line 9416: expected 15 fields, saw 16\nSkipping line 9417: expected 15 fields, saw 16\nSkipping line 9418: expected 15 fields, saw 16\nSkipping line 9419: expected 15 fields, saw 16\nSkipping line 9420: expected 15 fields, saw 16\nSkipping line 9421: expected 15 fields, saw 16\nSkipping line 9422: expected 15 fields, saw 16\nSkipping line 9423: expected 15 fields, saw 16\nSkipping line 9424: expected 15 fields, saw 16\nSkipping line 9425: expected 15 fields, saw 16\nSkipping line 9426: expected 15 fields, saw 16\nSkipping line 9427: expected 15 fields, saw 16\nSkipping line 9428: expected 15 fields, saw 16\nSkipping line 9429: expected 15 fields, saw 16\nSkipping line 9430: expected 15 fields, saw 16\nSkipping line 9431: expected 15 fields, saw 16\nSkipping line 9432: expected 15 fields, saw 16\nSkipping line 9433: expected 15 fields, saw 16\nSkipping line 9434: expected 15 fields, saw 16\nSkipping line 9435: expected 15 fields, saw 16\nSkipping line 9436: expected 15 fields, saw 16\nSkipping line 9437: expected 15 fields, saw 16\nSkipping line 9438: expected 15 fields, saw 16\nSkipping line 9439: expected 15 fields, saw 16\nSkipping line 9440: expected 15 fields, saw 16\nSkipping line 9441: expected 15 fields, saw 16\nSkipping line 9442: expected 15 fields, saw 16\nSkipping line 9443: expected 15 fields, saw 16\nSkipping line 9444: expected 15 fields, saw 16\nSkipping line 9445: expected 15 fields, saw 16\nSkipping line 9446: expected 15 fields, saw 16\nSkipping line 9447: expected 15 fields, saw 16\nSkipping line 9448: expected 15 fields, saw 16\nSkipping line 9449: expected 15 fields, saw 16\nSkipping line 9450: expected 15 fields, saw 16\nSkipping line 9451: expected 15 fields, saw 16\nSkipping line 9452: expected 15 fields, saw 16\nSkipping line 9453: expected 15 fields, saw 16\nSkipping line 9454: expected 15 fields, saw 16\nSkipping line 9455: expected 15 fields, saw 16\nSkipping line 9456: expected 15 fields, saw 16\nSkipping line 9457: expected 15 fields, saw 16\nSkipping line 9458: expected 15 fields, saw 16\nSkipping line 9459: expected 15 fields, saw 16\nSkipping line 9460: expected 15 fields, saw 16\nSkipping line 9461: expected 15 fields, saw 16\nSkipping line 9462: expected 15 fields, saw 16\nSkipping line 9463: expected 15 fields, saw 16\nSkipping line 9464: expected 15 fields, saw 16\nSkipping line 9465: expected 15 fields, saw 16\nSkipping line 9466: expected 15 fields, saw 16\nSkipping line 9467: expected 15 fields, saw 16\nSkipping line 9468: expected 15 fields, saw 16\nSkipping line 9469: expected 15 fields, saw 16\nSkipping line 9470: expected 15 fields, saw 16\nSkipping line 9471: expected 15 fields, saw 16\nSkipping line 9472: expected 15 fields, saw 16\n'

In [23]:
#check the dtypes
df.dtypes

Date_Time        datetime64[ns]
CO(GT)                  float64
PT08.S1(CO)               int64
NMHC(GT)                  int64
C6H6(GT)                float64
PT08.S2(NMHC)             int64
NOx(GT)                   int64
PT08.S3(NOx)              int64
NO2(GT)                   int64
PT08.S4(NO2)              int64
PT08.S5(O3)               int64
T                       float64
RH                      float64
AH                      float64
dtype: object

In [24]:
df

,Date_Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004-03-10 18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,2004-03-10 19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,2004-03-10 20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,2004-03-10 21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,2004-03-10 22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888
5,2004-03-10 23:00:00,1.2,1197,38,4.7,750,89,1337,96,1393,949,11.2,59.2,0.7848
6,2004-03-11 00:00:00,1.2,1185,31,3.6,690,62,1462,77,1333,733,11.3,56.8,0.7603
7,2004-03-11 01:00:00,1.0,1136,31,3.3,672,62,1453,76,1333,730,10.7,60.0,0.7702
8,2004-03-11 02:00:00,0.9,1094,24,2.3,609,45,1579,60,1276,620,10.7,59.7,0.7648
9,2004-03-11 03:00:00,0.6,1010,19,1.7,561,-200,1705,-200,1235,501,10.3,60.2,0.7517
10,2004-03-11 04:00:00,-200.0,1011,14,1.3,527,21,1818,34,1197,445,10.1,60.5,0.7465
11,2004-03-11 05:00:00,0.7,1066,8,1.1,512,16,1918,28,1182,422,11.0,56.2,0.7366
12,2004-03-11 06:00:00,0.7,1052,16,1.6,553,34,1738,48,1221,472,10.5,58.1,0.7353
13,2004-03-11 07:00:00,1.1,1144,29,3.2,667,98,1490,82,1339,730,10.2,59.6,0.7417
14,2004-03-11 08:00:00,2.0,1333,64,8.0,900,174,1136,112,1517,1102,10.8,57.4,0.7408
15,2004-03-11 09:00:00,2.2,1351,87,9.5,960,129,1079,101,1583,1028,10.5,60.6,0.7691
16,2004-03-11 10:00:00,1.7,1233,77,6.3,827,112,1218,98,1446,860,10.8,58.4,0.7552
17,2004-03-11 11:00:00,1.5,1179,43,5.0,762,95,1328,92,1362,671,10.5,57.9,0.7352
18,2004-03-11 12:00:00,1.6,1236,61,5.2,774,104,1301,95,1401,664,9.5,66.8,0.7951
19,2004-03-11 13:00:00,1.9,1286,63,7.3,869,146,1162,112,1537,799,8.3,76.4,0.8393
20,2004-03-11 14:00:00,2.9,1371,164,11.5,1034,207,983,128,1730,1037,8.0,81.1,0.8736
21,2004-03-11 15:00:00,2.2,1310,79,8.8,933,184,1082,126,1647,946,8.3,79.8,0.8778
22,2004-03-11 16:00:00,2.2,1292,95,8.3,912,193,1103,131,1591,957,9.7,71.2,0.8569
23,2004-03-11 17:00:00,2.9,1383,150,11.2,1020,243,1008,135,1719,1104,9.8,67.6,0.8185
24,2004-03-11 18:00:00,4.8,1581,307,20.8,1319,281,799,151,2083,1409,10.3,64.2,0.8065
25,2004-03-11 19:00:00,6.9,1776,461,27.4,1488,383,702,172,2333,1704,9.7,69.3,0.8319
26,2004-03-11 20:00:00,6.1,1640,401,24.0,1404,351,743,165,2191,1654,9.6,67.8,0.8133
27,2004-03-11 21:00:00,3.9,1313,197,12.8,1076,240,957,136,1707,1285,9.1,64.0,0.7419
28,2004-03-11 22:00:00,1.5,965,61,4.7,749,94,1325,85,1333,821,8.2,63.4,0.6905
29,2004-03-11 23:00:00,1.0,913,26,2.6,629,47,1565,53,1252,552,8.2,60.8,0.6657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9327,2005-04-03 09:00:00,1.2,1022,-200,4.1,715,192,806,118,1004,831,17.8,30.7,0.6205
9328,2005-04-03 10:00:00,1.4,970,-200,3.4,677,166,888,113,931,613,21.1,23.7,0.5875
9329,2005-04-03 11:00:00,1.3,1000,-200,5.3,779,171,805,115,1001,640,24.0,19.3,0.5673
9330,2005-04-03 12:00:00,1.4,996,-200,5.3,781,177,806,124,985,631,26.5,16.4,0.5594
9331,2005-04-03 13:00:00,1.0,928,-200,3.8,701,119,926,86,902,456,28.7,13.7,0.5302
9332,2005-04-03 14:00:00,1.0,933,-200,4.2,722,121,899,87,890,450,28.5,13.1,0.5002
9333,2005-04-03 15:00:00,1.1,956,-200,5.4,783,142,857,100,896,516,30.0,11.1,0.4624
9334,2005-04-03 16:00:00,1.3,968,-200,6.3,826,197,867,132,898,548,29.4,10.4,0.4192
9335,2005-04-03 17:00:00,1.4,953,-200,6.1,817,242,872,156,891,603,28.9,9.9,0.3866
9336,2005-04-03 18:00:00,1.2,1015,-200,4.6,743,190,851,138,981,597,22.8,21.7,0.5945
9337,2005-04-03 19:00:00,2.7,1248,-200,11.1,1018,367,599,181,1289,1167,19.9,33.0,0.7608
9338,2005-04-03 20:00:00,2.5,1180,-200,7.9,894,355,636,187,1200,1372,17.5,40.7,0.8073
9339,2005-04-03 21:00:00,1.5,1102,-200,6.0,812,235,693,158,1178,1042,16.4,46.6,0.8642
9340,2005-04-03 22:00:00,1.6,1116,-200,5.8,803,233,696,153,1173,1055,15.5,49.0,0.8579
9341,2005-04-03 23:00:00,1.2,1100,-200,5.1,769,170,722,128,1147,1049,14.3,52.5,0.8497
9342,2005-04-04 00:00:00,0.9,1012,-200,3.5,683,117,801,93,1073,816,14.2,51.4,0.8275
9343,2005-04-04 01:00:00,0.6,944,-200,1.9,579,70,925,58,1002,598,13.8,51.2,0.8058
9344,2005-04-04 02:00:00,0.5,912,-200,1.5,544,69,959,55,1002,573,12.1,56.3,0.7927
9345,2005-04-04 03:00:00,0.4,887,-200,1.1,508,62,1047,51,974,549,11.3,58.9,0.7888
9346,2005-04-04 04:00:00,-200.0,864,-200,0.8,478,52,1116,43,958,489,11.8,56.0,0.7743
9347,2005-04-04 05:00:00,0.5,888,-200,1.3,528,77,1077,53,987,578,10.4,59.9,0.7550
9348,2005-04-04 06:00:00,1.1,1031,-200,4.4,730,182,760,93,1129,905,9.5,63.1,0.7531
9349,2005-04-04 07:00:00,4.0,1384,-200,17.4,1221,594,470,155,1600,1457,9.7,61.9,0.7446
9350,2005-04-04 08:00:00,5.0,1446,-200,22.4,1362,586,415,174,1777,1705,13.5,48.9,0.7553
9351,2005-04-04 09:00:00,3.9,1297,-200,13.6,1102,523,507,187,1375,1583,18.2,36.3,0.7487
9352,2005-04-04 10:00:00,3.1,1314,-200,13.5,1101,472,539,190,1374,1729,21.9,29.3,0.7568
9353,2005-04-04 11:00:00,2.4,1163,-200,11.4,1027,353,604,179,1264,1269,24.3,23.7,0.7119
9354,2005-04-04 12:00:00,2.4,1142,-200,12.4,1063,293,603,175,1241,1092,26.9,18.3,0.6406
9355,2005-04-04 13:00:00,2.1,1003,-200,9.5,961,235,702,156,1041,770,28.3,13.5,0.5139
9356,2005-04-04 14:00:00,2.2,1071,-200,11.9,1047,265,654,168,1129,816,28.5,13.1,0.5028

In [25]:
df['Date_Time'] = pd.to_datetime(df.Date_Time , format = '%d/%m/%Y %H.%M.%S')
data = df.drop(['Date_Time'], axis=1)
data.index = df.Date_Time

In [33]:
#missing value treatment
cols = data.columns
for j in cols:
    for i in range(0,len(data)):
        if data[j][i] == -200:
            data[j][i] = data[j][i-1]

In [35]:
data

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
Date_Time,,,,,,,,,,,,,
2004-03-10 18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
2004-03-10 19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2004-03-10 20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
2004-03-10 21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
2004-03-10 22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888
2004-03-10 23:00:00,1.2,1197,38,4.7,750,89,1337,96,1393,949,11.2,59.2,0.7848
2004-03-11 00:00:00,1.2,1185,31,3.6,690,62,1462,77,1333,733,11.3,56.8,0.7603
2004-03-11 01:00:00,1.0,1136,31,3.3,672,62,1453,76,1333,730,10.7,60.0,0.7702
2004-03-11 02:00:00,0.9,1094,24,2.3,609,45,1579,60,1276,620,10.7,59.7,0.7648
2004-03-11 03:00:00,0.6,1010,19,1.7,561,45,1705,60,1235,501,10.3,60.2,0.7517
2004-03-11 04:00:00,0.6,1011,14,1.3,527,21,1818,34,1197,445,10.1,60.5,0.7465
2004-03-11 05:00:00,0.7,1066,8,1.1,512,16,1918,28,1182,422,11.0,56.2,0.7366
2004-03-11 06:00:00,0.7,1052,16,1.6,553,34,1738,48,1221,472,10.5,58.1,0.7353
2004-03-11 07:00:00,1.1,1144,29,3.2,667,98,1490,82,1339,730,10.2,59.6,0.7417
2004-03-11 08:00:00,2.0,1333,64,8.0,900,174,1136,112,1517,1102,10.8,57.4,0.7408
2004-03-11 09:00:00,2.2,1351,87,9.5,960,129,1079,101,1583,1028,10.5,60.6,0.7691
2004-03-11 10:00:00,1.7,1233,77,6.3,827,112,1218,98,1446,860,10.8,58.4,0.7552
2004-03-11 11:00:00,1.5,1179,43,5.0,762,95,1328,92,1362,671,10.5,57.9,0.7352
2004-03-11 12:00:00,1.6,1236,61,5.2,774,104,1301,95,1401,664,9.5,66.8,0.7951
2004-03-11 13:00:00,1.9,1286,63,7.3,869,146,1162,112,1537,799,8.3,76.4,0.8393
2004-03-11 14:00:00,2.9,1371,164,11.5,1034,207,983,128,1730,1037,8.0,81.1,0.8736
2004-03-11 15:00:00,2.2,1310,79,8.8,933,184,1082,126,1647,946,8.3,79.8,0.8778
2004-03-11 16:00:00,2.2,1292,95,8.3,912,193,1103,131,1591,957,9.7,71.2,0.8569
2004-03-11 17:00:00,2.9,1383,150,11.2,1020,243,1008,135,1719,1104,9.8,67.6,0.8185
2004-03-11 18:00:00,4.8,1581,307,20.8,1319,281,799,151,2083,1409,10.3,64.2,0.8065
2004-03-11 19:00:00,6.9,1776,461,27.4,1488,383,702,172,2333,1704,9.7,69.3,0.8319
2004-03-11 20:00:00,6.1,1640,401,24.0,1404,351,743,165,2191,1654,9.6,67.8,0.8133
2004-03-11 21:00:00,3.9,1313,197,12.8,1076,240,957,136,1707,1285,9.1,64.0,0.7419
2004-03-11 22:00:00,1.5,965,61,4.7,749,94,1325,85,1333,821,8.2,63.4,0.6905
2004-03-11 23:00:00,1.0,913,26,2.6,629,47,1565,53,1252,552,8.2,60.8,0.6657
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005-04-03 09:00:00,1.2,1022,275,4.1,715,192,806,118,1004,831,17.8,30.7,0.6205
2005-04-03 10:00:00,1.4,970,275,3.4,677,166,888,113,931,613,21.1,23.7,0.5875
2005-04-03 11:00:00,1.3,1000,275,5.3,779,171,805,115,1001,640,24.0,19.3,0.5673
2005-04-03 12:00:00,1.4,996,275,5.3,781,177,806,124,985,631,26.5,16.4,0.5594
2005-04-03 13:00:00,1.0,928,275,3.8,701,119,926,86,902,456,28.7,13.7,0.5302
2005-04-03 14:00:00,1.0,933,275,4.2,722,121,899,87,890,450,28.5,13.1,0.5002
2005-04-03 15:00:00,1.1,956,275,5.4,783,142,857,100,896,516,30.0,11.1,0.4624
2005-04-03 16:00:00,1.3,968,275,6.3,826,197,867,132,898,548,29.4,10.4,0.4192
2005-04-03 17:00:00,1.4,953,275,6.1,817,242,872,156,891,603,28.9,9.9,0.3866
2005-04-03 18:00:00,1.2,1015,275,4.6,743,190,851,138,981,597,22.8,21.7,0.5945
2005-04-03 19:00:00,2.7,1248,275,11.1,1018,367,599,181,1289,1167,19.9,33.0,0.7608
2005-04-03 20:00:00,2.5,1180,275,7.9,894,355,636,187,1200,1372,17.5,40.7,0.8073
2005-04-03 21:00:00,1.5,1102,275,6.0,812,235,693,158,1178,1042,16.4,46.6,0.8642
2005-04-03 22:00:00,1.6,1116,275,5.8,803,233,696,153,1173,1055,15.5,49.0,0.8579
2005-04-03 23:00:00,1.2,1100,275,5.1,769,170,722,128,1147,1049,14.3,52.5,0.8497
2005-04-04 00:00:00,0.9,1012,275,3.5,683,117,801,93,1073,816,14.2,51.4,0.8275
2005-04-04 01:00:00,0.6,944,275,1.9,579,70,925,58,1002,598,13.8,51.2,0.8058
2005-04-04 02:00:00,0.5,912,275,1.5,544,69,959,55,1002,573,12.1,56.3,0.7927
2005-04-04 03:00:00,0.4,887,275,1.1,508,62,1047,51,974,549,11.3,58.9,0.7888
2005-04-04 04:00:00,0.4,864,275,0.8,478,52,1116,43,958,489,11.8,56.0,0.7743
2005-04-04 05:00:00,0.5,888,275,1.3,528,77,1077,53,987,578,10.4,59.9,0.7550
2005-04-04 06:00:00,1.1,1031,275,4.4,730,182,760,93,1129,905,9.5,63.1,0.7531
2005-04-04 07:00:00,4.0,1384,275,17.4,1221,594,470,155,1600,1457,9.7,61.9,0.7446
2005-04-04 08:00:00,5.0,1446,275,22.4,1362,586,415,174,1777,1705,13.5,48.9,0.7553
2005-04-04 09:00:00,3.9,1297,275,13.6,1102,523,507,187,1375,1583,18.2,36.3,0.7487
2005-04-04 10:00:00,3.1,1314,275,13.5,1101,472,539,190,1374,1729,21.9,29.3,0.7568
2005-04-04 11:00:00,2.4,1163,275,11.4,1027,353,604,179,1264,1269,24.3,23.7,0.7119
2005-04-04 12:00:00,2.4,1142,275,12.4,1063,293,603,175,1241,1092,26.9,18.3,0.6406
2005-04-04 13:00:00,2.1,1003,275,9.5,961,235,702,156,1041,770,28.3,13.5,0.5139
2005-04-04 14:00:00,2.2,1071,275,11.9,1047,265,654,168,1129,816,28.5,13.1,0.5028

In [42]:
#checking stationarity
from statsmodels.tsa.vector_ar.vecm import coint_johansen
#since the test works for only 12 variables, I have randomly dropped
#in the next iteration, I would drop another and check the eigenvalues
johan_test_temp = data.drop([ 'CO(GT)'], axis=1)
coint_johansen(johan_test_temp,-1,1).eig

array([1.75510896e-01, 1.52389933e-01, 1.15120416e-01, 1.04126281e-01,
       9.29485509e-02, 6.89397159e-02, 5.77070988e-02, 3.43554214e-02,
       3.05980659e-02, 1.18697142e-02, 2.46766099e-03, 7.09584856e-05])

In [43]:
johan_test_temp.head(2)

,PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
Date_Time,,,,,,,,,,,,
2004-03-10 18:00:00,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
2004-03-10 19:00:00,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255

In [55]:
#creating the train and validation set
train = data[:int(0.8*(len(data)))]
valid = data[int(0.8*(len(data))):]

#fit the model
from statsmodels.tsa.vector_ar.var_model import VAR

model = VAR(endog=train)
model_fit = model.fit()

# make prediction on validation
prediction = model_fit.forecast(model_fit.y, steps=len(valid))

C:\Users\sumon\Anaconda3\envs\tensorflow\lib\site-packages\statsmodels\tsa\base\tsa_model.py:171: ValueWarning: No frequency information was provided, so inferred frequency H will be used.
  % freq, ValueWarning)

In [62]:
from math import sqrt
from sklearn.metrics import mean_squared_error
pred = pd.DataFrame(index=range(0,len(prediction)),columns=[cols])
for j in range(0,13):
    for i in range(0, len(prediction)):
        pred.iloc[i][j] = prediction[i][j]

#check rmse
for i in cols:
    print('rmse value for', i, 'is : ', sqrt(mean_squared_error(pred[i], valid[i])))

rmse value for CO(GT) is :  1.4086888836875395
rmse value for PT08.S1(CO) is :  205.89558284022644
rmse value for NMHC(GT) is :  6.673548711351738
rmse value for C6H6(GT) is :  7.1300872487053635
rmse value for PT08.S2(NMHC) is :  277.8484437680044
rmse value for NOx(GT) is :  214.78322340910108
rmse value for PT08.S3(NOx) is :  244.95769661939238
rmse value for NO2(GT) is :  66.69695211709386
rmse value for PT08.S4(NO2) is :  490.0838893409434
rmse value for PT08.S5(O3) is :  446.51541648882727
rmse value for T is :  10.721325795592657
rmse value for RH is :  17.11167624817325
rmse value for AH is :  0.5216247245182354

In [87]:
#make final predictions
model = VAR(endog=data)
model_fit = model.fit()
yhat = model_fit.forecast(model_fit.y, steps=5) #next 5 forecast
print(yhat)

[[2.34596328e+00 1.08633212e+03 2.80762173e+02 1.24130779e+01
  1.05535947e+03 2.80882233e+02 6.59534851e+02 1.68444418e+02
  1.15918056e+03 8.50845529e+02 2.73639014e+01 1.55311062e+01
  5.15317053e-01]
 [2.45308371e+00 1.09701970e+03 2.84860181e+02 1.26808042e+01
  1.05798069e+03 2.93265167e+02 6.66191599e+02 1.68520527e+02
  1.18047398e+03 8.80226856e+02 2.63058958e+01 1.77966232e+01
  5.27377242e-01]
 [2.52881822e+00 1.10419777e+03 2.87641649e+02 1.27763638e+01
  1.05651409e+03 3.02654521e+02 6.73675534e+02 1.68229199e+02
  1.19528761e+03 9.04734692e+02 2.53214196e+01 1.99101731e+01
  5.38878549e-01]
 [2.57938356e+00 1.10874388e+03 2.89392031e+02 1.27529209e+01
  1.05219269e+03 3.09532654e+02 6.81729036e+02 1.67598574e+02
  1.20540194e+03 9.24982666e+02 2.44055266e+01 2.18844523e+01
  5.49769526e-01]
 [2.60995661e+00 1.11133845e+03 2.90344425e+02 1.26491506e+01
  1.04594002e+03 3.14342095e+02 6.90130990e+02 1.66671502e+02
  1.21213722e+03 9.41571389e+02 2.35532502e+01 2.37310011e+01
  5.60032552e-01]]

C:\Users\sumon\Anaconda3\envs\tensorflow\lib\site-packages\statsmodels\tsa\base\tsa_model.py:171: ValueWarning: No frequency information was provided, so inferred frequency H will be used.
  % freq, ValueWarning)

In [88]:
model_fit.y[0]

array([2.600e+00, 1.360e+03, 1.500e+02, 1.190e+01, 1.046e+03, 1.660e+02,
       1.056e+03, 1.130e+02, 1.692e+03, 1.268e+03, 1.360e+01, 4.890e+01,
       7.578e-01])

In [89]:
pred.iloc[0]

CO(GT)           0.887831
PT08.S1(CO)        841.93
NMHC(GT)          271.627
C6H6(GT)          1.98243
PT08.S2(NMHC)      595.81
NOx(GT)           136.653
PT08.S3(NOx)      1119.79
NO2(GT)           87.8809
PT08.S4(NO2)      829.686
PT08.S5(O3)       545.725
T                 10.5476
RH                34.9086
AH               0.437327
Name: 0, dtype: object

In [90]:
data.iloc[0]

CO(GT)              2.6000
PT08.S1(CO)      1360.0000
NMHC(GT)          150.0000
C6H6(GT)           11.9000
PT08.S2(NMHC)    1046.0000
NOx(GT)           166.0000
PT08.S3(NOx)     1056.0000
NO2(GT)           113.0000
PT08.S4(NO2)     1692.0000
PT08.S5(O3)      1268.0000
T                  13.6000
RH                 48.9000
AH                  0.7578
Name: 2004-03-10 18:00:00, dtype: float64

In [91]:
for i in yhat[0]:
    print(i)

2.3459632768009353
1086.332115461929
280.7621730551785
12.413077928437808
1055.3594665160217
280.8822326451255
659.5348509636115
168.44441821354042
1159.1805581860376
850.8455285801379
27.363901374899804
15.531106151454274
0.5153170531015014

In [92]:
for i in yhat[1]:
    print(i)

2.4530837074663534
1097.0197024416138
284.86018112431725
12.680804245527213
1057.9806881319241
293.26516706643616
666.1915994591577
168.52052689527335
1180.473980201036
880.2268559981935
26.30589578154842
17.79662319545404
0.5273772420386397

In [93]:
for i in yhat[2]:
    print(i)

2.528818219207576
1104.197766924193
287.64164863261345
12.776363840590086
1056.5140903018769
302.65452142971895
673.675533862074
168.22919926314214
1195.2876065978248
904.7346921469932
25.32141958701607
19.910173056017495
0.5388785493508662

In [94]:
for i in yhat[3]:
    print(i)

2.579383562620558
1108.743881798183
289.392030844036
12.752920947193555
1052.1926892737183
309.5326539427982
681.7290358590965
167.59857437280516
1205.4019440899103
924.9826656943242
24.405526638502426
21.884452330327775
0.5497695257787651